version: '3'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - db.env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - database-data:/var/lib/postgresql/data/

  app:
    build: .
    ports:
      - 8080:8080
    restart: unless-stopped
    volumes:
      - ./images:/app/images
    environment:
      - TOKEN_TTL=24h
#      - PRODUCTION=true
    depends_on:
      - db

volumes:
  database-data:
  redis-data:
