version: '3'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - db.env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - database-data:/var/lib/postgresql/data/

  redis:
    image: redis
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis-data:/data
    ports:
      - "127.0.0.1:6379:6379"
    restart: always

  app:
    build: .
    ports:
      - 8080:8080
    restart: unless-stopped
    volumes:
      - ./images:/app/images
    environment:
      - TOKEN_TTL=5m
#      - PRODUCTION=true
    depends_on:
      - db
      - redis

volumes:
  database-data:
  redis-data:
