FROM golang:alpine
WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download
RUN go get -u github.com/google/wire/cmd/wire
COPY cmd cmd
COPY pkg pkg
RUN cd cmd/reverse-market && wire
ENTRYPOINT CGO_ENABLED=0 go test -v ./cmd/reverse-market/


