// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/reverse-market/backend/pkg/database/postgres"

	_ "github.com/reverse-market/backend/doc"
)

// Injectors from wire.go:

func initApp() (*Application, func(), error) {
	mainConfig, err := getConfig()
	if err != nil {
		return nil, nil, err
	}
	mainLoggers := NewLoggers()
	manager := NewJwtManager(mainConfig)
	postgresConfig := NewPostgresConfig(mainConfig)
	pool, cleanup, err := postgres.NewPsqlPool(postgresConfig)
	if err != nil {
		return nil, nil, err
	}
	userRepository := &postgres.UserRepository{
		DB: pool,
	}
	application := &Application{
		config:  mainConfig,
		loggers: mainLoggers,
		tokens:  manager,
		users:   userRepository,
	}
	return application, func() {
		cleanup()
	}, nil
}
